import { expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { PAGE_MARKDOWN } from "./pageMarkdown";

const ROOT = join(import.meta.dir, "..", "..");
const ORCA_REFERENCE_PATH = join(ROOT, "ORCA_REFERENCE.md");

test("uses canonical codex effort values and thinkingLevel naming", () => {
  expect(PAGE_MARKDOWN).toContain(
    "Codex effort values: `low|medium|high|xhigh`",
  );
  expect(PAGE_MARKDOWN).toContain("thinkingLevel?:");
  expect(PAGE_MARKDOWN).not.toContain("extra-high");
  expect(PAGE_MARKDOWN).not.toContain("codex.thinking:");
});

test("is generated from CLI and public type references", () => {
  expect(PAGE_MARKDOWN).toContain(
    "Generated by `node scripts/generate-docs-reference.mjs`",
  );
  expect(PAGE_MARKDOWN).toContain(
    "This section is generated from the Commander command tree",
  );
  expect(PAGE_MARKDOWN).toContain("Usage: orca run [options] [goal]");
  expect(PAGE_MARKDOWN).toContain("export interface OrcaConfig");
});

test("PAGE_MARKDOWN is loaded from ORCA_REFERENCE.md", () => {
  const reference = readFileSync(ORCA_REFERENCE_PATH, "utf8");
  expect(PAGE_MARKDOWN).toBe(reference);
});
